# <center><u>**CERT x466-003**</u>: Data Storytelling<br>AI Job Market Data Exploration and Storytelling</center>

<figure style="text-align: center;">
    <img src="notebook_images/ai_jobMarket01.png" alt="AI Job Market">
</figure>

---

---

---

## DOWNLOAD AND UNZIP DATASET FROM KAGGLE

In [1]:
from dotenv import load_dotenv
load_dotenv()

import kaggle
kaggle.api.dataset_download_files('shree0910/ai-and-data-science-job-market-dataset-20202026', path='./data', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/shree0910/ai-and-data-science-job-market-dataset-20202026

---

## GPU ACCELERATION

In [1]:
%load_ext cudf.pandas
%load_ext cuml.accel

---

## IMPORTS

In [2]:
import pandas as pd
import cudf
import numpy as np
import cuml

import plotly.express as px
import plotly.graph_objects as go

---

## DATASET LOADING AND INITIAL LOOK

In [8]:
ai_df = pd.read_csv('data/boot_ai_job_market_dataset.csv')

In [9]:
print(ai_df.shape)
ai_df.head(88)

(15518, 19)

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,0,Machine Learning Engineer,Enterprise,Finance,Canada,Onsite,Senior,12,PhD,1,1,0,0,0,139715,12,2020,Medium,2
1,1,Data Engineer,MNC,Retail,Australia,Hybrid,Senior,6,Master,1,1,1,0,1,149778,12,2022,Low,1
2,2,Data Scientist,Medium,Retail,India,Onsite,Senior,5,Bachelor,0,0,0,0,1,114691,6,2021,High,7
3,3,Business Analyst,Medium,E-commerce,USA,Onsite,Senior,10,Master,0,0,0,0,0,97989,9,2026,High,7
4,4,Data Analyst,Startup,Finance,Australia,Onsite,Entry,3,Master,0,0,1,1,0,80678,8,2023,High,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,83,Business Analyst,Enterprise,E-commerce,Germany,Remote,Entry,10,Master,1,0,1,0,1,75242,3,2020,Medium,5
84,84,Data Engineer,MNC,Technology,India,Onsite,Entry,6,PhD,1,1,1,1,1,114292,5,2026,High,8
85,85,AI Engineer,Medium,Technology,Singapore,Remote,Mid,9,PhD,1,1,0,0,1,129860,6,2023,Medium,1
86,86,AI Engineer,Startup,Healthcare,USA,Onsite,Senior,14,PhD,1,1,1,1,0,170320,4,2026,High,2
87,87,Data Scientist,Medium,Healthcare,Canada,Hybrid,Senior,2,Master,1,0,1,0,1,123402,11,2025,Low,5

In [13]:
dtypes_df = pd.DataFrame(ai_df.dtypes, columns=['Dtype'])
null_df = pd.DataFrame(ai_df.isnull().sum(), columns=['Null Count'])
nunique_df = pd.DataFrame(ai_df.nunique(), columns=['Unique Count'])
decription_df = pd.DataFrame(ai_df.describe())

In [14]:
dtypes_df

                       Dtype
job_id                 int64
job_title             object
company_size          object
company_industry      object
country               object
remote_type           object
experience_level      object
years_experience       int64
education_level       object
skills_python          int64
skills_sql             int64
skills_ml              int64
skills_deep_learning   int64
skills_cloud           int64
salary                 int64
job_posting_month      int64
job_posting_year       int64
hiring_urgency        object
job_openings           int64

In [15]:
null_df

                      Null Count
job_id                         0
job_title                      0
company_size                   0
company_industry               0
country                        0
remote_type                    0
experience_level               0
years_experience               0
education_level                0
skills_python                  0
skills_sql                     0
skills_ml                      0
skills_deep_learning           0
skills_cloud                   0
salary                         0
job_posting_month              0
job_posting_year               0
hiring_urgency                 0
job_openings                   0

In [16]:
nunique_df

                      Unique Count
job_id                       15518
job_title                        6
company_size                     4
company_industry                 6
country                          7
remote_type                      3
experience_level                 3
years_experience                15
education_level                  3
skills_python                    2
skills_sql                       2
skills_ml                        2
skills_deep_learning             2
skills_cloud                     2
salary                        7758
job_posting_month               12
job_posting_year                 7
hiring_urgency                   3
job_openings                     9

In [17]:
decription_df

,job_id,years_experience,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,job_openings
count,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000
mean,7758.500000,7.040211,0.495618,0.502900,0.512308,0.499356,0.510246,113544.975512,6.513662,2022.984470,4.998325
std,4479.805074,4.307095,0.499997,0.500008,0.499865,0.500016,0.499911,31455.844782,3.472228,1.991042,2.589880
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45083.000000,1.000000,2020.000000,1.000000
25%,3879.250000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,89494.250000,4.000000,2021.000000,3.000000
50%,7758.500000,7.000000,0.000000,1.000000,1.000000,0.000000,1.000000,113436.000000,6.000000,2023.000000,5.000000
75%,11637.750000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,134997.000000,10.000000,2025.000000,7.000000
max,15517.000000,14.000000,1.000000,1.000000,1.000000,1.000000,1.000000,204143.000000,12.000000,2026.000000,9.000000

---