# <center><u>**CERT x466-003**</u>: Data Storytelling<br>AI Job Market Data Exploration and Storytelling</center>

<figure style="text-align: center;">
    <img src="notebook_images/ai_jobMarket01.png" alt="AI Job Market">
</figure>

---

---

---

## DOWNLOAD AND UNZIP DATASET FROM KAGGLE

In [1]:
from dotenv import load_dotenv
load_dotenv()

import kaggle
kaggle.api.dataset_download_files('shree0910/ai-and-data-science-job-market-dataset-20202026', path='./data', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/shree0910/ai-and-data-science-job-market-dataset-20202026

---

## GPU ACCELERATION

In [1]:
%load_ext cudf.pandas
%load_ext cuml.accel

---

## IMPORTS

In [3]:
import pandas as pd
import cudf
import numpy as np
import cuml

import plotly.express as px
import plotly.graph_objects as go

---

## DATASET LOADING AND INITIAL LOOK

In [54]:
ai_df = cudf.read_csv('./data/boot_ai_job_market_dataset.csv')

In [55]:
print(ai_df.shape)
ai_df.head(33)

(15518, 19)

,job_id,job_title,company_size,company_industry,country,remote_type,experience_level,years_experience,education_level,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,hiring_urgency,job_openings
0,0,Machine Learning Engineer,Enterprise,Finance,Canada,Onsite,Senior,12,PhD,1,1,0,0,0,139715,12,2020,Medium,2
1,1,Data Engineer,MNC,Retail,Australia,Hybrid,Senior,6,Master,1,1,1,0,1,149778,12,2022,Low,1
2,2,Data Scientist,Medium,Retail,India,Onsite,Senior,5,Bachelor,0,0,0,0,1,114691,6,2021,High,7
3,3,Business Analyst,Medium,E-commerce,USA,Onsite,Senior,10,Master,0,0,0,0,0,97989,9,2026,High,7
4,4,Data Analyst,Startup,Finance,Australia,Onsite,Entry,3,Master,0,0,1,1,0,80678,8,2023,High,5
5,5,Data Analyst,Startup,Education,Australia,Hybrid,Entry,7,PhD,1,0,1,0,1,71758,7,2020,Low,3
6,6,Data Analyst,Medium,Technology,India,Onsite,Entry,12,Master,1,0,0,1,1,79746,6,2020,Medium,4
7,7,Data Analyst,Enterprise,Retail,Australia,Onsite,Entry,11,PhD,0,0,0,0,1,63639,9,2026,Medium,5
8,8,Business Analyst,Startup,Technology,Singapore,Hybrid,Entry,14,PhD,1,1,1,0,1,73061,9,2022,Medium,2
9,9,Data Scientist,Enterprise,Retail,Canada,Remote,Mid,11,Bachelor,1,0,1,0,0,89001,6,2026,Medium,4
10,10,Data Analyst,Medium,Retail,USA,Hybrid,Senior,4,PhD,0,1,1,1,1,139690,11,2022,High,3
11,11,Business Analyst,Startup,Retail,UK,Onsite,Senior,7,PhD,1,1,0,1,1,122884,4,2022,Low,6
12,12,Data Scientist,MNC,Education,Singapore,Hybrid,Mid,13,Master,1,0,0,1,0,108174,5,2026,Medium,1
13,13,AI Engineer,MNC,Finance,USA,Hybrid,Mid,0,Master,0,1,0,0,0,130819,3,2021,High,7
14,14,Machine Learning Engineer,Medium,Technology,Singapore,Hybrid,Mid,10,Bachelor,0,1,0,0,0,119491,11,2022,High,8
15,15,AI Engineer,Medium,Healthcare,Canada,Onsite,Senior,0,Bachelor,0,1,1,0,1,164677,12,2025,Low,6
16,16,Business Analyst,Medium,Finance,Singapore,Onsite,Senior,8,Master,1,0,1,0,1,122389,11,2020,Medium,6
17,17,Business Analyst,Startup,Retail,Singapore,Remote,Entry,12,PhD,1,1,1,1,0,79735,7,2024,High,2
18,18,Data Analyst,Enterprise,Healthcare,Singapore,Hybrid,Senior,9,Bachelor,0,1,0,0,0,99920,5,2025,High,9
19,19,Machine Learning Engineer,Enterprise,Technology,Australia,Remote,Mid,9,Bachelor,0,0,0,0,1,127746,2,2024,Medium,5
20,20,Business Analyst,Startup,Technology,Canada,Remote,Entry,1,Bachelor,1,0,1,0,0,65657,10,2026,High,9
21,21,AI Engineer,Startup,E-commerce,India,Onsite,Entry,7,PhD,1,0,1,1,1,126221,10,2020,High,8
22,22,Data Analyst,MNC,Healthcare,India,Hybrid,Mid,12,Master,1,0,0,1,1,118648,12,2020,High,7
23,23,AI Engineer,MNC,Technology,Singapore,Remote,Mid,1,Bachelor,0,0,0,1,1,155891,5,2021,Low,3
24,24,Business Analyst,Startup,Healthcare,USA,Hybrid,Entry,12,PhD,0,0,0,0,1,57746,6,2026,Medium,2
25,25,Business Analyst,MNC,Finance,Australia,Hybrid,Mid,2,PhD,0,1,1,0,0,113007,10,2022,Low,5
26,26,Data Scientist,Enterprise,Healthcare,USA,Onsite,Entry,10,Bachelor,1,1,1,0,0,62959,9,2022,High,7
27,27,Data Engineer,Startup,Education,Australia,Onsite,Senior,12,Master,0,0,1,1,1,135590,12,2026,High,8
28,28,AI Engineer,Enterprise,Technology,UK,Hybrid,Mid,8,Master,1,0,1,1,1,152803,6,2026,High,9
29,29,AI Engineer,Medium,Education,India,Onsite,Entry,6,PhD,1,0,1,1,0,117773,11,2021,High,9
30,30,Data Analyst,Enterprise,Technology,Canada,Hybrid,Mid,2,Bachelor,0,1,1,1,0,102199,5,2023,High,5
31,31,Data Analyst,Medium,Technology,Australia,Hybrid,Senior,3,Master,1,1,1,0,0,117226,6,2025,High,8
32,32,AI Engineer,Enterprise,Technology,USA,Onsite,Senior,6,PhD,0,0,1,0,1,169634,6,2021,High,9

In [56]:
dtypes_df = pd.DataFrame(ai_df.dtypes, columns=['Dtype'])
null_df = pd.DataFrame(ai_df.isnull().sum(), columns=['Null Count'])
nunique_df = pd.DataFrame(ai_df.nunique(), columns=['Unique Count'])
decription_df = pd.DataFrame(ai_df.describe())

In [57]:
dtypes_df

                       Dtype
job_id                 int64
job_title             object
company_size          object
company_industry      object
country               object
remote_type           object
experience_level      object
years_experience       int64
education_level       object
skills_python          int64
skills_sql             int64
skills_ml              int64
skills_deep_learning   int64
skills_cloud           int64
salary                 int64
job_posting_month      int64
job_posting_year       int64
hiring_urgency        object
job_openings           int64

In [58]:
null_df

                      Null Count
job_id                         0
job_title                      0
company_size                   0
company_industry               0
country                        0
remote_type                    0
experience_level               0
years_experience               0
education_level                0
skills_python                  0
skills_sql                     0
skills_ml                      0
skills_deep_learning           0
skills_cloud                   0
salary                         0
job_posting_month              0
job_posting_year               0
hiring_urgency                 0
job_openings                   0

In [59]:
nunique_df

                      Unique Count
job_id                       15518
job_title                        6
company_size                     4
company_industry                 6
country                          7
remote_type                      3
experience_level                 3
years_experience                15
education_level                  3
skills_python                    2
skills_sql                       2
skills_ml                        2
skills_deep_learning             2
skills_cloud                     2
salary                        7758
job_posting_month               12
job_posting_year                 7
hiring_urgency                   3
job_openings                     9

In [60]:
decription_df

,job_id,years_experience,skills_python,skills_sql,skills_ml,skills_deep_learning,skills_cloud,salary,job_posting_month,job_posting_year,job_openings
count,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000,15518.000000
mean,7758.500000,7.040211,0.495618,0.502900,0.512308,0.499356,0.510246,113544.975512,6.513662,2022.984470,4.998325
std,4479.805074,4.307095,0.499997,0.500008,0.499865,0.500016,0.499911,31455.844782,3.472228,1.991042,2.589880
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,45083.000000,1.000000,2020.000000,1.000000
25%,3879.250000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,89494.250000,4.000000,2021.000000,3.000000
50%,7758.500000,7.000000,0.000000,1.000000,1.000000,0.000000,1.000000,113436.000000,6.000000,2023.000000,5.000000
75%,11637.750000,11.000000,1.000000,1.000000,1.000000,1.000000,1.000000,134997.000000,10.000000,2025.000000,7.000000
max,15517.000000,14.000000,1.000000,1.000000,1.000000,1.000000,1.000000,204143.000000,12.000000,2026.000000,9.000000

---